language: node_js # 设置语言

node_js: 
    - "13.2.0" # 设置相应版本

# cache:
#     apt: true
#     directories:
#         - node_modules # 设置缓存，传说会在构建的时候快一些

git:
    depth: 1
    submodules: true

before_install:
    - export TZ='Asia/Shanghai'
    - npm install hexo-cli -g

install:
    - npm install # 安装hexo及插件

script:
    - hexo clean # 清除
    - hexo g # 生成

after_script:
    # - git clone https://${GH_REF} pub_web # 因为我有两个仓库，先将发布服务的仓库clone下来，
    # - cp -rf public/* pub_web/ # 将源博客仓库(blog.git)目录下的public文件夹下的文件复制到发布服务的仓库(chenzhijun.github.com.git)中
    # - cd pub_web # 进入到git仓库
    - cd ./public
    - echo "superj.site" > CNAME
    - git init
    - git config user.name "overoptimus"
    - git config user.email "1040570917@qq.com"
    - git add .
    - git commit -am "Travis CI Auto Builder :$(date '+%Y-%m-%d %H:%M:%S')" # 零时区，+8小时
    - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master
    - git push --force --quiet "https://EBlvrRYUzD:${CD_TOKEN}@${CD_REF}" master:master
branches:
    only:
        - master #只监测master分支,这是我自己的博客，所以就用的master分支了。
env:
    global:
        - GH_REF: github.com/overoptimus/overoptimus.github.io.git #设置GH_REF，注意更改yourname,GITHUB_TOKEN:就是我们在travis-ci仓库中配置的环境变量
        - GITHUB_TOKEN: "${github_token}"
        - CD_REF: e.coding.net/overoptimus/overoptimus.git
        - CD_TOKEN: "${cd_token}"